config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :games
  root 'games#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.fetch(:game, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_with(model: game, local: true) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
 <p id="notice"><%= notice %></p>

<h1>$<span id="moneyDisplay">0</span></h1>

<br><input type="button" value="Produce" id="createButton" /><br>
------------------------------------------------------------------<br>

<p><span id="sheetsDisplay">0</span> sheets of paper produced.<span id="displayReams"></span></p>
<p>Profit: $<span id="profPerSec"></span></p>
------------------------------------------------------------------<br>
<input type="button" value="$<" onclick="priceDown()" class="priceChange" id="pDown">
<span id="reamPriceDisplay"></span>
<input type="button" value="$>" onclick="priceUp()" class="priceChange" id="pDown"><br>
------------------------------------------------------------------<br>
<span id="ttlUpsCnt" value=""></span><br>
<p id="nextUpDisplay"></p>
<input type="button" value="" onclick="clickUp(this)" class="initHdn" id="clickUp"/>
<input type="button" value="" onclick="autoClickUp(this)" class="initHdn" id="autoUp"/>
<br><input type="button" value="" onclick="qClickUp(this)" class="initHdn" id="qClickUp"/>
<input type="button" value="" onclick="qAutoUp(this)" class="initHdn" id="qAutoUp"/>
<br><input type="button" value="" onclick="saleUp(this)" class="initHdn" id="saleUp">



<br><input type="button" value="Save" onclick="clearStorage(this)" id="save">
<input type="button" value="Load" onclick="clearLoop(this)" id="load">

<script type="text/javascript">

  var sheets = 0;
  var sheetsButton = document.getElementById("createButton");
  var display = document.getElementById("sheetsDisplay");

  var nextUpDisplay = document.getElementById("nextUpDisplay");
  var clickPrice = 100;
  var clickMult = 1;
  var clickCount = 0;
  var qClickUpPrice = 500000;
  var qClickUpCount = 0;

  var upsPriceArray;

  var up;
  var autoPrice = 10;
  var autoRate = 2500;
  var autoMult = 1;
  var autoCount = 0;
  var qAutoUpPrice = 1000000000000;
  var qAutoUpCount = 0;

  var perReam = 50;
  var reamDisplay = document.getElementById("displayReams");
  var reamPrice = 20;
  var reamPriceDisplay = document.getElementById("reamPriceDisplay");

  var money = 0;
  var moneyDisplay = document.getElementById("moneyDisplay");
  var profPerSec = document.getElementById("profPerSec");
  var saleMult = 1;
  var saleRate = 10000;
  var selling;
  var loop;
  var saleUpPrice = 2500;
  var saleUpCount = 0;

  window.onload = function() {
    var array = document.getElementsByClassName("initHdn");
    for (var i = 0; i < array.length; i++) {
      var item = array[i];
      item.hidden = true;
    }
    saleLoop = setInterval(baseLoop, saleRate);
    reamPriceDisplay.innerHTML = "$" + reamPrice + " per Ream (" + perReam + " Sheets per Ream)";
    reamDisplay.innerHTML = " (" + Math.floor(sheets / perReam) + " Reams in Storage)";
    nextUpDisplay.innerHTML = "Next Upgrade at $10";
    document.getElementById("ttlUpsCnt").innerHTML = "Upgrades: 0"
    profPerSec.innerHTML = "0";
  }

  function checkUps() {
    var ttlUps = clickCount + autoCount + qClickUpCount + qAutoUpCount + saleUpCount;
    if (money >= clickPrice) {
      document.getElementById("clickUp").hidden = false;
      document.getElementById("clickUp").value = "Update Method ($" + clickPrice + ")";
    }
    if (money >= autoPrice) {
      document.getElementById("autoUp").hidden = false;
      document.getElementById("autoUp").value = "Improve Technology ($" + autoPrice + ")";
      nextUpDisplay.hidden = true;
    }
    if (money >= qClickUpPrice) {
      document.getElementById("qClickUp").hidden = false;
      document.getElementById("qClickUp").value = "Technological Advancement " + (qClickUpCount + 1) + " ($" + qClickUpPrice + ")";
      nextUpDisplay.hidden = true;
    }
    if (money >= qAutoUpPrice) {
      document.getElementById("qAutoUp").hidden = false;
      document.getElementById("qAutoUp").value = "Apply Method to Manufacturing " + (qAutoUpCount + 1) +" ($" + qAutoUpPrice + ")";
      nextUpDisplay.hidden = true;
    }
    if (money >= saleUpPrice) {
      document.getElementById("saleUp").hidden = false;
      document.getElementById("saleUp").value = "Improve Marketing " + (saleUpCount + 1) + " ($" + saleUpPrice + ")";
      nextUpDisplay.hidden = true;
    }
    profPerSec.innerHTML = profit();
    display.innerHTML = sheets.toString();
    moneyDisplay.innerHTML = money.toString();
    reamPriceDisplay.innerHTML = "$" + reamPrice + " per Ream (" + perReam + " Sheets per Ream)";
    reamDisplay.innerHTML = " (" + Math.floor(sheets / perReam) + " Reams in Storage)";
    document.getElementById("ttlUpsCnt").innerHTML = "Upgrades: " + ttlUps;
  }

  function baseLoop() {
    clearInterval(selling);
    selling = setInterval(baseSale(), saleRate);
    checkUps();
  }

  createButton.onclick = function() {
    sheets += clickMult;
    display.innerHTML = sheets.toString();
    moneyDisplay.innerHTML = money.toString();
    reamPriceDisplay.innerHTML = "$" + reamPrice + " per Ream (" + perReam + " Sheets per Ream)";
    reamDisplay.innerHTML = " (" + Math.floor(sheets / perReam) + " Reams in Storage)";
    checkUps();
  }

  function nextUpDetermine() {
    if (clickPrice == autoPrice) {
      upsPriceArray = [clickPrice, qClickUpPrice, autoPrice, qAutoUpPrice, saleUpPrice];
      nextUpDisplay.hidden = false;
      nextUpDisplay.innerHTML = "Next Upgrade at $" + Math.min(...upsPriceArray);
    }
  }

  function clickUp(button) {
    if (money >= clickPrice) {
      money -= clickPrice;
      button.hidden = true;
      clickPrice *= 10;
      clickMult *= 5;
      clickCount += 1;
      checkUps();
      nextUpDetermine();
    }
  }

  function autoClick() {
    up = setInterval(function() {
      sheets += autoMult;
      display.innerHTML = sheets.toString();
      moneyDisplay.innerHTML = money.toString();
      reamPriceDisplay.innerHTML = "$" + reamPrice + " per Ream (" + perReam + " Sheets per Ream)";
      reamDisplay.innerHTML = " (" + Math.floor(sheets / perReam) + " Reams in Storage)";
      checkUps();
    }, autoRate);
  }

  function autoClickUp(button) {
    if (money >= autoPrice) {
      money -= autoPrice;
      button.hidden = true;
      autoPrice *= 10;
      autoRate /= 5;
      autoCount += 1;
      if (autoRate <= 0.01) {
        autoMult *= 10;
      }
      autoClick();
      nextUpDetermine();
    }
  }

  function qClickUp(button) {
    money -= qClickUpPrice;
    clickMult *= 50;
    button.hidden = true;
    qClickUpCount += 1;
    qClickUpPrice *= 100000;
    autoPrice *= 10;
    clickPrice *= 10;
    nextUpDetermine();
  }

  function qAutoUp(button) {
    money -= qAutoUpPrice;
    autoMult *= 10;
    button.hidden = true;
    qAutoUpCount += 1;
    qAutoUpPrice *= 100000;
    autoPrice *= 10;
    clickPrice *= 10;
    nextUpDetermine();
  }

  function baseSaleExe() {
    if (sheets >= perReam) {
      sheets -= perReam;
      money += reamPrice;
      moneyDisplay.innerHTML = money.toString();
      display.innerHTML = sheets.toString();
      reamPriceDisplay.innerHTML = "$" + reamPrice + " per Ream (" + perReam + " Sheets per Ream)";
      reamDisplay.innerHTML = " (" + Math.floor(sheets / perReam) + " Reams in Storage)";
      checkUps();
    }
  }

  function baseSale() {
    if (sheets >= perReam) {
      var delay = setTimeout(baseSaleExe, saleRate);
    }
  }

  function priceDown() {
    if (reamPrice >= 1) {
      reamPrice -= 1;
      saleRate /= 1.25;
      checkUps();
      reamPriceDisplay.value = reamPrice;
      clearInterval(saleLoop);
      saleLoop = setInterval(baseLoop, saleRate);
    }
  }

  function priceUp() {
    reamPrice += 1;
    saleRate *= 1.25;
    checkUps();
    reamPriceDisplay.value = reamPrice;
    clearInterval(saleLoop);
    saleLoop = setInterval(baseLoop, saleRate);
  }

  function saleUp(button) {
    money -= saleUpPrice;
    button.hidden = true;
    saleUpPrice *= 100;
    saleRate /= 100;
    saleUpCount += 1;
    checkUps();
    clearInterval(saleLoop);
    saleLoop = setInterval(baseLoop, saleRate);
    nextUpDetermine();
  }

  function profit() {
    if (clickCount + autoCount + qClickUpCount + qAutoUpCount + saleUpCount >= 1) {
      saleRateInSeconds = saleRate / 1000;
      return autoMult / saleRateInSeconds;
    }
  }

















  var key = 0;

  function clearStorage() {
    localStorage.clear()
    saveGame();
  }

  function saveGame() {
    key += 1;
    dataArray = [[sheets, clickPrice, clickMult, clickCount, qClickUpPrice, qClickUpCount, autoPrice, autoRate, autoMult, autoCount, qAutoUpPrice, qAutoUpCount, perReam, reamPrice, money, saleMult, saleRate, saleUpPrice, saleUpCount]];
    window.localStorage.setItem(key, JSON.stringify(dataArray));
    localStorage.setItem(key, dataArray);
    localStorage.setItem('lastkey', key);
  }

  function startLoop() {
    saleLoop = setInterval(baseLoop, saleRate);
    selling = setInterval(baseSale(), saleRate);
    up = setInterval(function() {
      sheets += autoMult;
      display.innerHTML = sheets.toString();
      moneyDisplay.innerHTML = money.toString();
      reamPriceDisplay.innerHTML = "$" + reamPrice + " per Ream (" + perReam + " Sheets per Ream)";
      reamDisplay.innerHTML = " (" + Math.floor(sheets / perReam) + " Reams in Storage)";
      checkUps();
    }, autoRate);
  }

  function setDelay() {
    var restart = setTimeout(startLoop(), 5000);
  }

  function clearLoop() {
    clearInterval(up);
    clearInterval(saleLoop);
    clearInterval(selling);
    loadGame();
  }

  function loadGame() {
    lastKey = localStorage.getItem('lastkey');
    savedData = localStorage.getItem(lastKey).split(",");
    sheets = parseInt(savedData[0]);
    clickPrice = parseInt(savedData[1]);
    clickMult = parseInt(savedData[2]);
    clickCount = parseInt(savedData[3]);
    qClickUpPrice = parseInt(savedData[4]);
    qClickUpCount = parseInt(savedData[5]);
    autoPrice = parseInt(savedData[6]);
    autoRate = parseInt(savedData[7]);
    autoMult = parseInt(savedData[8]);
    autoCount = parseInt(savedData[9]);
    qAutoUpPrice = parseInt(savedData[10]);
    qAutoUpCount = parseInt(savedData[11]);
    perReam = parseInt(savedData[12]);
    reamPrice = parseInt(savedData[13]);
    money = parseInt(savedData[14]);
    saleMult = parseInt(savedData[15]);
    saleRate = parseInt(savedData[16]);
    saleUpPrice = parseInt(savedData[17]);
    saleUpCount = parseInt(savedData[18]);
    upsPriceArray = [clickPrice, qClickUpPrice, autoPrice, qAutoUpPrice, saleUpPrice];
    setDelay();
    checkUps();
    nextUpDetermine();
  }

</script>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UniversalPaper</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>